### ISSUE TITLE
the invite link doesn't work if the url has a path component

### ISSUE THREAD

**Issue by stevedekorte** [SamPatt/HaveWords.ai#11]
e.g. it shows:

 https://stevedekorte.github.io/?room=ywv0dhdyj

instead of:

https://stevedekorte.github.io/HaveWords.ai/?room=ywv0dhdyj

**Comment by SamPatt** [comment]
We replaced paths with hashes and invite link generation no longer includes the hash, so this should be outdated now, closing.
